# Generated by Django 5.0.7 on 2024-07-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
