# Generated by Django 5.0.7 on 2024-08-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
